-- OFFICE5_MIG_TEST : temp table 

CREATE TABLE OFFICE5_MIG_TEST (
    DOCUNO VARCHAR2(20) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE NULL,
    TITLE VARCHAR2(200) NULL,
    CONTENT CLOB NULL,
    ATTFILENUM NUMBER(4,0) DEFAULT 0 NULL,
    STATUS CHAR(1) NULL
);

CREATE UNIQUE INDEX OFFICE5_MIG_TEST_PK ON OFFICE5_MIG_TEST (DOCUNO, TITLE);

