-- 1.작업한 마지막 문서번호 가져오기
select *
from OFFICE5_MIG_NUMBER
where save_type = 'M' and year = '2022';

-- 2.마지막 문서번호 기준으로 1000개 단위로 문서 마스터 정보 가져오기
SELECT *
FROM (
SELECT m.docuno, m.userid, u.name AS USERNAME, m.deptcode, d.deptname, m.formcode, f.FORMNAME, m.regdate, m.title, m.ATTFILENUM, m.status, m.content
FROM OA_EAPP_DOCUMAS M
	INNER JOIN (
		SELECT docuno AS DOCUNO 
		FROM OA_EAPP_DEPTDOCU
		WHERE docuno > '201307080855190133'
		UNION
		SELECT DRAFTNO AS DOCUNO
		FROM OA_EAPP_DEPTDOCU
		WHERE docuno > '201307080855190133'
	) DOC_NUMBER ON M.DOCUNO = DOC_NUMBER.DOCUNO
	LEFT OUTER JOIN O0_USER_MAST u ON m.USERID = u.USERID
	LEFT OUTER JOIN O0_USER_DEPT d ON m.DEPTCODE = d.DEPTCODE
	LEFT OUTER JOIN OA_EAPP_FORM f ON m.FORMCODE  = f.FORMCODE
WHERE M.docuno LIKE '2014%' AND M.docuno > '201409020938230083'
ORDER BY M.docuno ASC
) OUTER_TABLE
WHERE ROWNUM <= 1000;

-- 3.문서에 첨부된 파일 정보를 가져온다
SELECT *
FROM OA_EAPP_ATTACHFILE
WHERE docuno = '201409011607310083';

-- 4.복사할 파일이 이미 복사가 됬는지 확인하기 위한 조회
SELECT *
FROM OFFICE5_MIG_ATTACH
WHERE NEWFILENAME = 'F1409556699990.jpg';

-- 5.파일 복사가 완료된 정보를 table에 insert 한다. 단, 4번 조회한 값이 존재하지 않을 경우만 insert하다(docuno, filecode)
INSERT INTO OFFICE5_MIG_ATTACH
(DOCUNO, FILECODE, FILESIZE, ORIFILENAME, NEWFILENAME, ACTIONDATE)
VALUES('DOCUNO', 'FILECODE', 0, 'ORIFILENAME', 'NEWFILENAME', SYSDATE);

-- 6.개인함 정보를 조회한다
SELECT op.docuno, op.boxcode, op.userid, u.name AS username
FROM OA_EAPP_PRIDOCU op
	LEFT OUTER JOIN O0_USER_MAST u ON op.userid = u.USERID
WHERE op.DOCUNO = '201408201459270289';

-- 7.개인함 정보를 insert한다
INSERT INTO OFFICE5_BOX_PRIVATE
(DOCUNO, USERID, USERNAME, BOXCODE, ACTIONDATE)
VALUES('DOCUNO', 'USERID', 'USERNAME', 'BOXCODE', SYSDATE );

-- 8.부서함 정보를 조회한다
SELECT od.docuno, od.boxcode, od.deptcode, d1.deptname, od.SDEPTCODE, d2.deptname AS SDEPTNAME, od.SUSERID, u.name AS SUSERNAME, od.status, od.DRAFTNO
FROM OA_EAPP_DEPTDOCU od 
	LEFT OUTER JOIN O0_USER_DEPT d1 ON od.DEPTCODE = d1.DEPTCODE
	LEFT OUTER JOIN O0_USER_DEPT d2 ON od.SDEPTCODE = d2.DEPTCODE
	LEFT OUTER JOIN O0_USER_MAST u ON od.SUSERID = u.USERID
WHERE od.DOCUNO  = '202206201655350394';

-- 9.부서함 정보를 insert한다
INSERT INTO GWDB.OFFICE5_BOX_DEPT
(DOCUNO, BOXCODE, DEPTCODE, DEPTNAME, SDEPTCODE, SDEPTNAME, SUSERID, SUSERNAME, STATUS, DRAFTNO, ACTIONDATE)
VALUES('DOCUNO', 'BOXCODE', 'DEPTCODE', 'DEPTNAME', 'SDEPTCODE', 'SDEPTNAME', 'SUSERID', 'SUSERNAME', 'STATUS', 'DRAFTNO', SYSDATE );

-- 10.pdf 파일 경로를 포함한 완료 문서정보를 테이블에 저장한다
INSERT INTO OFFICE5_MIG_APP
(DOCUNO, USERID, USERNAME, DEPTCODE, DEPTNAME, FORMCODE, FORMNAME, REGDATE, TITLE, CONTENT, ATTFILENUM, STATUS, ACTIONDATE)
VALUES('DOCUNO', 'USERID', 'USERNAME', 'DEPTCODE', 'DEPTNAME', 'FORMCODE', 'FORMNAME', 'REGDATE', 'TITLE', 'CONTENT', 0 , 'STATUS', SYSDATE );

-- 11.문서건단위 완료정보를 저장한다
INSERT INTO OFFICE5_MIG_JOB_SUCCESS
(DOCUNO, ACTIONDATE)
VALUES('DOCUNO', SYSDATE );

-- 12.페이징 쿼리 조회 기준의 시작이되는 docuno를 테이블에 저장한다 : 완료정보를 번호만 테이블에 저장한다
UPDATE OFFICE5_MIG_NUMBER
SET LAST_DOCUNO = 'DOCUNO'
WHERE "YEAR"='YEAR' AND SAVE_TYPE='M';

 -- 99.step 단위로 에러 정보를 저장해야한다
INSERT INTO OFFICE5_MIG_JOB_FAIL
(DOCUNO, JOBSTEP, ERRORMESSAGE, ACTIONDATE)
VALUES('DOCUNO', 0 , 'ERRORMESSAGE', SYSDATE );
