-- 부서 테이블
SELECT *
FROM O0_USER_DEPT
WHERE DEPTCODE =  '37';

-- 사용자 테이블
SELECT *
FROM O0_USER_MAST
WHERE userid = 'ijeong22';

-- 부서함 매핑 테이블
SELECT *
FROM OA_EAPP_PRIDOCU;
WHERE BOXCODE ='BX';

-- 부서함 매핑 테이블
SELECT *
FROM OA_EAPP_DEPTDOCU;
WHERE BOXCODE ='BX';

-- 문서 마스터 테이블
SELECT *
FROM OA_EAPP_DOCUMAS oed
WHERE DOCUNO = '201907080855190133';

-- 페이징 쿼리
SELECT *
FROM (
	SELECT *
	FROM OA_EAPP_DOCUMAS
	ORDER BY docuno ASC
) A
WHERE ROWNUM <= 100;

-- 양식 템플릿 테이블
SELECT *
FROM OA_EAPP_FORM;

-- 문서번호로 비교해서 추출하기
SELECT *
	FROM OA_EAPP_DOCUMAS
	WHERE docuno > '201409020938230083' AND DOCUNO < '201409020939190554';

-- 첨부파일 조회
SELECT *
FROM OA_EAPP_ATTACHFILE
WHERE FILECODE  = 'ERPCODE';

-- 부서문서함의 전체 docuno
select *
from  (
    SELECT docuno AS DOCUNO 
    FROM OA_EAPP_DEPTDOCU
    WHERE docuno > '201307080855190133'
    UNION
    SELECT DRAFTNO AS DOCUNO
    FROM OA_EAPP_DEPTDOCU
    WHERE docuno > '201307080855190133'
) DOC_NUMBER;


-- 오직 개인함에만 존재하는 문서 확인
SELECT count(*)
FROM OA_EAPP_PRIDOCU
WHERE docuno NOT IN (
	SELECT docuno
    FROM OA_EAPP_DEPTDOCU
    WHERE docuno IS NOT null
) AND docuno NOT IN (
	SELECT draftno
    FROM OA_EAPP_DEPTDOCU
    WHERE draftno IS NOT null
);